import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./_Components/Navbar/Navbar";
import ReduxProvider from "@/Rdeux/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: " ذِكر",
  description: "Generated by create next app",
  
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
       <head>
        <link rel="icon" href="/public/finalogo.png" />
      </head>
      <body dir='rtl'  className={inter.className}>
      <Navbar/>
      <ReduxProvider>
        {children}
      </ReduxProvider>
        </body>
    </html>
  );
}
