import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./_Components/Navbar/Navbar";
import ReduxProvider from "@/Rdeux/Provider";
import Year from "./_Components/Year/Year";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Zekr",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body dir='rtl'  className={inter.className}>
      <Navbar/>
      <ReduxProvider>
        {children}
      </ReduxProvider>
      {/* <Year/> */}
        </body>
    </html>
  );
}
